spring:
  application:
    name: board

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:d030517!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:HhEzSBZk3P3MY3bWse4yI3vXFte5UAJVCJtUKx3Wsrc=}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:1800000}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:1209600000}

app:
  file:
    storage: local

    local:
      root-path: ${LOCAL_FILE_ROOT:./uploads}
      public-base-url: ${LOCAL_FILE_BASE_URL:http://localhost:8080/files}

  image:
    max-count: 5
    max-size-bytes: 10485760